// Package cartclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package cartclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Oauth2Scopes oauth2ContextKey = "oauth2.Scopes"
)

// Cart defines model for Cart.
type Cart struct {
	ID        string     `json:"id"`
	Items     []CartItem `json:"items"`
	Subtotal  float32    `json:"subtotal"`
	UpdatedAt string     `json:"updatedAt,omitempty"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	BookID   string `json:"bookId"`
	Quantity int    `json:"quantity"`
}

// Error defines model for Error.
type Error struct {
	Code        int    `json:"code"`
	Description string `json:"description,omitempty"`
	Message     string `json:"message"`
	MoreInfo    string `json:"moreInfo,omitempty"`
}

// oauth2ContextKey is the context key for oauth2 security scheme
type oauth2ContextKey string

// AddMyCartItemJSONBody defines parameters for AddMyCartItem.
type AddMyCartItemJSONBody struct {
	BookID   string `json:"bookId"`
	Quantity int    `json:"quantity"`
}

// UpdateMyCartItemJSONBody defines parameters for UpdateMyCartItem.
type UpdateMyCartItemJSONBody struct {
	Quantity int `json:"quantity"`
}

// AddMyCartItemJSONRequestBody defines body for AddMyCartItem for application/json ContentType.
type AddMyCartItemJSONRequestBody AddMyCartItemJSONBody

// UpdateMyCartItemJSONRequestBody defines body for UpdateMyCartItem for application/json ContentType.
type UpdateMyCartItemJSONRequestBody UpdateMyCartItemJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClearMyCart request
	ClearMyCart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMyCart request
	GetMyCart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddMyCartItemWithBody request with any body
	AddMyCartItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddMyCartItem(ctx context.Context, body AddMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveMyCartItem request
	RemoveMyCartItem(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateMyCartItemWithBody request with any body
	UpdateMyCartItemWithBody(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateMyCartItem(ctx context.Context, bookID string, body UpdateMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClearMyCart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClearMyCartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMyCart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMyCartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMyCartItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMyCartItemRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMyCartItem(ctx context.Context, body AddMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMyCartItemRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RemoveMyCartItem(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveMyCartItemRequest(c.Server, bookID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMyCartItemWithBody(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMyCartItemRequestWithBody(c.Server, bookID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMyCartItem(ctx context.Context, bookID string, body UpdateMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMyCartItemRequest(c.Server, bookID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewClearMyCartRequest generates requests for ClearMyCart
func NewClearMyCartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/cart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMyCartRequest generates requests for GetMyCart
func NewGetMyCartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/cart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddMyCartItemRequest calls the generic AddMyCartItem builder with application/json body
func NewAddMyCartItemRequest(server string, body AddMyCartItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddMyCartItemRequestWithBody(server, "application/json", bodyReader)
}

// NewAddMyCartItemRequestWithBody generates requests for AddMyCartItem with any type of body
func NewAddMyCartItemRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/cart/items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRemoveMyCartItemRequest generates requests for RemoveMyCartItem
func NewRemoveMyCartItemRequest(server string, bookID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bookId", bookID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/cart/items/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateMyCartItemRequest calls the generic UpdateMyCartItem builder with application/json body
func NewUpdateMyCartItemRequest(server string, bookID string, body UpdateMyCartItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateMyCartItemRequestWithBody(server, bookID, "application/json", bodyReader)
}

// NewUpdateMyCartItemRequestWithBody generates requests for UpdateMyCartItem with any type of body
func NewUpdateMyCartItemRequestWithBody(server string, bookID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bookId", bookID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/cart/items/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ClearMyCartWithResponse request
	ClearMyCartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ClearMyCartResponse, error)

	// GetMyCartWithResponse request
	GetMyCartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMyCartResponse, error)

	// AddMyCartItemWithBodyWithResponse request with any body
	AddMyCartItemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMyCartItemResponse, error)

	AddMyCartItemWithResponse(ctx context.Context, body AddMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMyCartItemResponse, error)

	// RemoveMyCartItemWithResponse request
	RemoveMyCartItemWithResponse(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*RemoveMyCartItemResponse, error)

	// UpdateMyCartItemWithBodyWithResponse request with any body
	UpdateMyCartItemWithBodyWithResponse(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMyCartItemResponse, error)

	UpdateMyCartItemWithResponse(ctx context.Context, bookID string, body UpdateMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMyCartItemResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ClearMyCartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Error
}

// Status returns HTTPResponse.Status
func (r ClearMyCartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClearMyCartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ClearMyCartResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMyCartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cart
}

// Status returns HTTPResponse.Status
func (r GetMyCartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMyCartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMyCartResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddMyCartItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cart
	JSON400      *Error
	JSON401      *Error
}

// Status returns HTTPResponse.Status
func (r AddMyCartItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddMyCartItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddMyCartItemResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RemoveMyCartItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cart
	JSON401      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r RemoveMyCartItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveMyCartItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RemoveMyCartItemResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateMyCartItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cart
	JSON400      *Error
	JSON401      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r UpdateMyCartItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateMyCartItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateMyCartItemResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ClearMyCartWithResponse request returning *ClearMyCartResponse
func (c *ClientWithResponses) ClearMyCartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ClearMyCartResponse, error) {
	rsp, err := c.ClearMyCart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClearMyCartResponse(rsp)
}

// GetMyCartWithResponse request returning *GetMyCartResponse
func (c *ClientWithResponses) GetMyCartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMyCartResponse, error) {
	rsp, err := c.GetMyCart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMyCartResponse(rsp)
}

// AddMyCartItemWithBodyWithResponse request with arbitrary body returning *AddMyCartItemResponse
func (c *ClientWithResponses) AddMyCartItemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMyCartItemResponse, error) {
	rsp, err := c.AddMyCartItemWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMyCartItemResponse(rsp)
}

func (c *ClientWithResponses) AddMyCartItemWithResponse(ctx context.Context, body AddMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMyCartItemResponse, error) {
	rsp, err := c.AddMyCartItem(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMyCartItemResponse(rsp)
}

// RemoveMyCartItemWithResponse request returning *RemoveMyCartItemResponse
func (c *ClientWithResponses) RemoveMyCartItemWithResponse(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*RemoveMyCartItemResponse, error) {
	rsp, err := c.RemoveMyCartItem(ctx, bookID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveMyCartItemResponse(rsp)
}

// UpdateMyCartItemWithBodyWithResponse request with arbitrary body returning *UpdateMyCartItemResponse
func (c *ClientWithResponses) UpdateMyCartItemWithBodyWithResponse(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMyCartItemResponse, error) {
	rsp, err := c.UpdateMyCartItemWithBody(ctx, bookID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMyCartItemResponse(rsp)
}

func (c *ClientWithResponses) UpdateMyCartItemWithResponse(ctx context.Context, bookID string, body UpdateMyCartItemJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMyCartItemResponse, error) {
	rsp, err := c.UpdateMyCartItem(ctx, bookID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMyCartItemResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseClearMyCartResponse parses an HTTP response from a ClearMyCartWithResponse call
func ParseClearMyCartResponse(rsp *http.Response) (*ClearMyCartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClearMyCartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetMyCartResponse parses an HTTP response from a GetMyCartWithResponse call
func ParseGetMyCartResponse(rsp *http.Response) (*GetMyCartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMyCartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cart
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddMyCartItemResponse parses an HTTP response from a AddMyCartItemWithResponse call
func ParseAddMyCartItemResponse(rsp *http.Response) (*AddMyCartItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddMyCartItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cart
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRemoveMyCartItemResponse parses an HTTP response from a RemoveMyCartItemWithResponse call
func ParseRemoveMyCartItemResponse(rsp *http.Response) (*RemoveMyCartItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveMyCartItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cart
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateMyCartItemResponse parses an HTTP response from a UpdateMyCartItemWithResponse call
func ParseUpdateMyCartItemResponse(rsp *http.Response) (*UpdateMyCartItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateMyCartItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cart
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
