// Package inventoryclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package inventoryclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Oauth2Scopes oauth2ContextKey = "oauth2.Scopes"
)

// Defines values for ReservationStatus.
const (
	Held     ReservationStatus = "held"
	Released ReservationStatus = "released"
)

// Valid indicates whether the value is a known member of the ReservationStatus enum.
func (e ReservationStatus) Valid() bool {
	switch e {
	case Held:
		return true
	case Released:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code        int    `json:"code"`
	Description string `json:"description,omitempty"`
	Message     string `json:"message"`
	MoreInfo    string `json:"moreInfo,omitempty"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	BookID   string            `json:"bookId"`
	ID       string            `json:"id"`
	OrderID  string            `json:"orderId"`
	Quantity int               `json:"quantity"`
	Status   ReservationStatus `json:"status"`
}

// ReservationStatus defines model for Reservation.Status.
type ReservationStatus string

// StockLevel defines model for StockLevel.
type StockLevel struct {
	BookID           string `json:"bookId"`
	QuantityOnHand   int    `json:"quantityOnHand"`
	QuantityReserved int    `json:"quantityReserved"`
}

// oauth2ContextKey is the context key for oauth2 security scheme
type oauth2ContextKey string

// ListReservationsParams defines parameters for ListReservations.
type ListReservationsParams struct {
	Limit  int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ReserveStockJSONBody defines parameters for ReserveStock.
type ReserveStockJSONBody struct {
	BookID   string `json:"bookId"`
	OrderID  string `json:"orderId"`
	Quantity int    `json:"quantity"`
}

// ListStockLevelsParams defines parameters for ListStockLevels.
type ListStockLevelsParams struct {
	Limit  int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SetStockLevelJSONBody defines parameters for SetStockLevel.
type SetStockLevelJSONBody struct {
	QuantityOnHand int `json:"quantityOnHand"`
}

// ReserveStockJSONRequestBody defines body for ReserveStock for application/json ContentType.
type ReserveStockJSONRequestBody ReserveStockJSONBody

// SetStockLevelJSONRequestBody defines body for SetStockLevel for application/json ContentType.
type SetStockLevelJSONRequestBody SetStockLevelJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListReservations request
	ListReservations(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReserveStockWithBody request with any body
	ReserveStockWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReserveStock(ctx context.Context, body ReserveStockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseReservation request
	ReleaseReservation(ctx context.Context, reservationID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListStockLevels request
	ListStockLevels(ctx context.Context, params *ListStockLevelsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStockLevel request
	GetStockLevel(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetStockLevelWithBody request with any body
	SetStockLevelWithBody(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetStockLevel(ctx context.Context, bookID string, body SetStockLevelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListReservations(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListReservationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReserveStockWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReserveStockRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReserveStock(ctx context.Context, body ReserveStockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReserveStockRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseReservation(ctx context.Context, reservationID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseReservationRequest(c.Server, reservationID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListStockLevels(ctx context.Context, params *ListStockLevelsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListStockLevelsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStockLevel(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockLevelRequest(c.Server, bookID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetStockLevelWithBody(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetStockLevelRequestWithBody(c.Server, bookID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetStockLevel(ctx context.Context, bookID string, body SetStockLevelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetStockLevelRequest(c.Server, bookID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListReservationsRequest generates requests for ListReservations
func NewListReservationsRequest(server string, params *ListReservationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReserveStockRequest calls the generic ReserveStock builder with application/json body
func NewReserveStockRequest(server string, body ReserveStockJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReserveStockRequestWithBody(server, "application/json", bodyReader)
}

// NewReserveStockRequestWithBody generates requests for ReserveStock with any type of body
func NewReserveStockRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseReservationRequest generates requests for ReleaseReservation
func NewReleaseReservationRequest(server string, reservationID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "reservationId", reservationID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s/release", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListStockLevelsRequest generates requests for ListStockLevels
func NewListStockLevelsRequest(server string, params *ListStockLevelsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock-levels")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockLevelRequest generates requests for GetStockLevel
func NewGetStockLevelRequest(server string, bookID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bookId", bookID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock-levels/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetStockLevelRequest calls the generic SetStockLevel builder with application/json body
func NewSetStockLevelRequest(server string, bookID string, body SetStockLevelJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetStockLevelRequestWithBody(server, bookID, "application/json", bodyReader)
}

// NewSetStockLevelRequestWithBody generates requests for SetStockLevel with any type of body
func NewSetStockLevelRequestWithBody(server string, bookID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bookId", bookID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock-levels/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ListReservationsWithResponse request
	ListReservationsWithResponse(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*ListReservationsResponse, error)

	// ReserveStockWithBodyWithResponse request with any body
	ReserveStockWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReserveStockResponse, error)

	ReserveStockWithResponse(ctx context.Context, body ReserveStockJSONRequestBody, reqEditors ...RequestEditorFn) (*ReserveStockResponse, error)

	// ReleaseReservationWithResponse request
	ReleaseReservationWithResponse(ctx context.Context, reservationID string, reqEditors ...RequestEditorFn) (*ReleaseReservationResponse, error)

	// ListStockLevelsWithResponse request
	ListStockLevelsWithResponse(ctx context.Context, params *ListStockLevelsParams, reqEditors ...RequestEditorFn) (*ListStockLevelsResponse, error)

	// GetStockLevelWithResponse request
	GetStockLevelWithResponse(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*GetStockLevelResponse, error)

	// SetStockLevelWithBodyWithResponse request with any body
	SetStockLevelWithBodyWithResponse(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetStockLevelResponse, error)

	SetStockLevelWithResponse(ctx context.Context, bookID string, body SetStockLevelJSONRequestBody, reqEditors ...RequestEditorFn) (*SetStockLevelResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListReservationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Count    int           `json:"count"`
		Data     []Reservation `json:"data"`
		Next     string        `json:"next,omitempty"`
		Previous string        `json:"previous,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListReservationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListReservationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListReservationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReserveStockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Reservation
	JSON400      *Error
	JSON401      *Error
}

// Status returns HTTPResponse.Status
func (r ReserveStockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReserveStockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReserveStockResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReleaseReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Reservation
	JSON401      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ReleaseReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReleaseReservationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListStockLevelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Count    int          `json:"count"`
		Data     []StockLevel `json:"data"`
		Next     string       `json:"next,omitempty"`
		Previous string       `json:"previous,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListStockLevelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListStockLevelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListStockLevelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetStockLevelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StockLevel
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetStockLevelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockLevelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetStockLevelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SetStockLevelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StockLevel
	JSON400      *Error
	JSON401      *Error
}

// Status returns HTTPResponse.Status
func (r SetStockLevelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetStockLevelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SetStockLevelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ListReservationsWithResponse request returning *ListReservationsResponse
func (c *ClientWithResponses) ListReservationsWithResponse(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*ListReservationsResponse, error) {
	rsp, err := c.ListReservations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListReservationsResponse(rsp)
}

// ReserveStockWithBodyWithResponse request with arbitrary body returning *ReserveStockResponse
func (c *ClientWithResponses) ReserveStockWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReserveStockResponse, error) {
	rsp, err := c.ReserveStockWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReserveStockResponse(rsp)
}

func (c *ClientWithResponses) ReserveStockWithResponse(ctx context.Context, body ReserveStockJSONRequestBody, reqEditors ...RequestEditorFn) (*ReserveStockResponse, error) {
	rsp, err := c.ReserveStock(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReserveStockResponse(rsp)
}

// ReleaseReservationWithResponse request returning *ReleaseReservationResponse
func (c *ClientWithResponses) ReleaseReservationWithResponse(ctx context.Context, reservationID string, reqEditors ...RequestEditorFn) (*ReleaseReservationResponse, error) {
	rsp, err := c.ReleaseReservation(ctx, reservationID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseReservationResponse(rsp)
}

// ListStockLevelsWithResponse request returning *ListStockLevelsResponse
func (c *ClientWithResponses) ListStockLevelsWithResponse(ctx context.Context, params *ListStockLevelsParams, reqEditors ...RequestEditorFn) (*ListStockLevelsResponse, error) {
	rsp, err := c.ListStockLevels(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListStockLevelsResponse(rsp)
}

// GetStockLevelWithResponse request returning *GetStockLevelResponse
func (c *ClientWithResponses) GetStockLevelWithResponse(ctx context.Context, bookID string, reqEditors ...RequestEditorFn) (*GetStockLevelResponse, error) {
	rsp, err := c.GetStockLevel(ctx, bookID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockLevelResponse(rsp)
}

// SetStockLevelWithBodyWithResponse request with arbitrary body returning *SetStockLevelResponse
func (c *ClientWithResponses) SetStockLevelWithBodyWithResponse(ctx context.Context, bookID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetStockLevelResponse, error) {
	rsp, err := c.SetStockLevelWithBody(ctx, bookID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetStockLevelResponse(rsp)
}

func (c *ClientWithResponses) SetStockLevelWithResponse(ctx context.Context, bookID string, body SetStockLevelJSONRequestBody, reqEditors ...RequestEditorFn) (*SetStockLevelResponse, error) {
	rsp, err := c.SetStockLevel(ctx, bookID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetStockLevelResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListReservationsResponse parses an HTTP response from a ListReservationsWithResponse call
func ParseListReservationsResponse(rsp *http.Response) (*ListReservationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListReservationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Count    int           `json:"count"`
			Data     []Reservation `json:"data"`
			Next     string        `json:"next,omitempty"`
			Previous string        `json:"previous,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReserveStockResponse parses an HTTP response from a ReserveStockWithResponse call
func ParseReserveStockResponse(rsp *http.Response) (*ReserveStockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReserveStockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Reservation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseReleaseReservationResponse parses an HTTP response from a ReleaseReservationWithResponse call
func ParseReleaseReservationResponse(rsp *http.Response) (*ReleaseReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Reservation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListStockLevelsResponse parses an HTTP response from a ListStockLevelsWithResponse call
func ParseListStockLevelsResponse(rsp *http.Response) (*ListStockLevelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListStockLevelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Count    int          `json:"count"`
			Data     []StockLevel `json:"data"`
			Next     string       `json:"next,omitempty"`
			Previous string       `json:"previous,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetStockLevelResponse parses an HTTP response from a GetStockLevelWithResponse call
func ParseGetStockLevelResponse(rsp *http.Response) (*GetStockLevelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockLevelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StockLevel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseSetStockLevelResponse parses an HTTP response from a SetStockLevelWithResponse call
func ParseSetStockLevelResponse(rsp *http.Response) (*SetStockLevelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetStockLevelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StockLevel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
