// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /books/{bookId}"
  | "DELETE /me/addresses/{addressId}"
  | "DELETE /me/cart"
  | "DELETE /me/cart/items/{bookId}"
  | "GET /books"
  | "GET /books/{bookId}"
  | "GET /health"
  | "GET /me/addresses"
  | "GET /me/cart"
  | "GET /me/notifications"
  | "GET /me/orders"
  | "GET /me/orders/{orderId}"
  | "GET /me/profile"
  | "GET /reservations"
  | "GET /stock-levels"
  | "GET /stock-levels/{bookId}"
  | "POST /books"
  | "POST /me/addresses"
  | "POST /me/cart/items"
  | "POST /me/notifications/{notificationId}/read"
  | "POST /me/orders"
  | "POST /notifications"
  | "POST /reservations"
  | "POST /reservations/{reservationId}/release"
  | "PUT /books/{bookId}"
  | "PUT /me/addresses/{addressId}"
  | "PUT /me/cart/items/{bookId}"
  | "PUT /me/profile"
  | "PUT /stock-levels/{bookId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /books/{bookId}": { kind: "scope", scope: "books:manage" },
  "DELETE /me/addresses/{addressId}": { kind: "scope", scope: "account:manage" },
  "DELETE /me/cart": { kind: "scope", scope: "cart:manage" },
  "DELETE /me/cart/items/{bookId}": { kind: "scope", scope: "cart:manage" },
  "GET /books": { kind: "public" },
  "GET /books/{bookId}": { kind: "public" },
  "GET /health": { kind: "public" },
  "GET /me/addresses": { kind: "scope", scope: "account:read" },
  "GET /me/cart": { kind: "scope", scope: "cart:read" },
  "GET /me/notifications": { kind: "scope", scope: "notifications:read" },
  "GET /me/orders": { kind: "scope", scope: "orders:read" },
  "GET /me/orders/{orderId}": { kind: "scope", scope: "orders:read" },
  "GET /me/profile": { kind: "scope", scope: "account:read" },
  "GET /reservations": { kind: "scope", scope: "stock:view-reservations" },
  "GET /stock-levels": { kind: "public" },
  "GET /stock-levels/{bookId}": { kind: "public" },
  "POST /books": { kind: "scope", scope: "books:manage" },
  "POST /me/addresses": { kind: "scope", scope: "account:manage" },
  "POST /me/cart/items": { kind: "scope", scope: "cart:manage" },
  "POST /me/notifications/{notificationId}/read": { kind: "scope", scope: "notifications:read" },
  "POST /me/orders": { kind: "scope", scope: "orders:create" },
  "POST /notifications": { kind: "scope", scope: "notifications:create" },
  "POST /reservations": { kind: "scope", scope: "stock:reserve" },
  "POST /reservations/{reservationId}/release": { kind: "scope", scope: "stock:reserve" },
  "PUT /books/{bookId}": { kind: "scope", scope: "books:manage" },
  "PUT /me/addresses/{addressId}": { kind: "scope", scope: "account:manage" },
  "PUT /me/cart/items/{bookId}": { kind: "scope", scope: "cart:manage" },
  "PUT /me/profile": { kind: "scope", scope: "account:manage" },
  "PUT /stock-levels/{bookId}": { kind: "scope", scope: "stock:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
